### ISSUE TITLE
We have detected you are using a third party modification, as a result your game has been closed [...]

### ISSUE THREAD

**Issue by MaciejK2** [Youded-byte/lunar-client-qt#23]
![obraz](https://github.com/Youded-byte/lunar-client-qt/assets/75207983/261451fc-5bbd-4338-a404-ce1dec8b45bb)

As in title, happens when built in weave is enabled. When I disable it, it just hangs on and I need to close it manually via crashing. Same applies when I add the newest weave, even without mods.

We have detected you are using a third party modification, as a result your game has been closed. Uninstall any third party modifications to continue using Lunar Client.

Lunar Ver.: Newest 1.7.10 (2.12.4-2401)

**Comment by Youded-byte** [comment]
You can use the following agent to fix it [https://github.com/koxx12-dev/LunarAntiAntiAgent/releases/download/1.0/LunarAntiAntiAgent.jar](https://github.com/koxx12-dev/LunarAntiAntiAgent/releases/download/1.0/LunarAntiAntiAgent.jar).
I won't include any fix for now, since Weave itself will update soon with an updated patch.
