### ISSUE TITLE
Can you make like the lunar qt 2.50

### ISSUE THREAD

**Issue by Iabdullah777** [Youded-byte/lunar-client-qt#25]
Its link 
https://github.com/Nilsen84/lcqt2/releases/tag/v2.5.0

![screenshot](https://github.com/Youded-byte/lunar-client-qt/assets/94728237/07692179-c5ad-427f-8b2e-cdfbf239df5e)

**Comment by Youded-byte** [comment]
The codebase is very different, and I dislike all electron "web" programs. Most "modules" are able to be downloaded from github as Weave mods anyway which works better because multiple creators can keep them up to date. The injection system is good, but it's an approach this project won't follow because it requires the use of the launcher which will be constantly changed and forcefully updates the game.
