### ISSUE TITLE
Doesn't detect Lunar

### ISSUE THREAD

**Issue by princessmortix** [Youded-byte/lunar-client-qt#5]
So, this fork doesn't detect my Lunar versions:

![image](https://user-images.githubusercontent.com/47502554/220741277-2345a8ef-b70f-4207-b45d-5fcc3647a143.png)

(But the original project does:)
![image](https://user-images.githubusercontent.com/47502554/220741358-8b2a8672-e212-419d-96c3-3890a0df7cb9.png)

I am doing something wrong?

**Comment by Youded-byte** [comment]
Do you have the newest version of lunar client installed? If not, updating it might fix. 

Otherwise could you provide the path in which lunar client is installed and the folders inside of it? (usually %userprofile%/.lunarclient/offline/multiver) There could be a problem finding your userprofile folder, or then something in parsing the lunarclient folder.

**Comment by princessmortix** [comment]
Working now on the latest version.
